clean:
	./gradlew clean

build:
	./gradlew installDist

check:
	./gradlew checkstyleMain

check-test:
	./gradlew checkstyleMain checkstyleTest

test:
	./gradlew test

report:
	./gradlew jacocoTestReport

run:
	./gradlew run

.PHONY: build